// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8SmavLoWry5iDA9fmA3uPfZf381H1RY',
    appId: '1:276842356711:web:3548b53c983544c6e76742',
    messagingSenderId: '276842356711',
    projectId: 'recycle-app-df66f',
    authDomain: 'recycle-app-df66f.firebaseapp.com',
    storageBucket: 'recycle-app-df66f.firebasestorage.app',
    measurementId: 'G-QJTSG068BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29DqH1fFeUV4KFzHGdsmipAxtqv-3znQ',
    appId: '1:276842356711:android:b0c43cafc65a2066e76742',
    messagingSenderId: '276842356711',
    projectId: 'recycle-app-df66f',
    storageBucket: 'recycle-app-df66f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhapy8ogZ7KAXB5wdSYpLm4dBpPWePzg',
    appId: '1:276842356711:ios:d022a83b5efcbc04e76742',
    messagingSenderId: '276842356711',
    projectId: 'recycle-app-df66f',
    storageBucket: 'recycle-app-df66f.firebasestorage.app',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhapy8ogZ7KAXB5wdSYpLm4dBpPWePzg',
    appId: '1:276842356711:ios:d022a83b5efcbc04e76742',
    messagingSenderId: '276842356711',
    projectId: 'recycle-app-df66f',
    storageBucket: 'recycle-app-df66f.firebasestorage.app',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp8SmavLoWry5iDA9fmA3uPfZf381H1RY',
    appId: '1:276842356711:web:aa9b49d8540aa53ce76742',
    messagingSenderId: '276842356711',
    projectId: 'recycle-app-df66f',
    authDomain: 'recycle-app-df66f.firebaseapp.com',
    storageBucket: 'recycle-app-df66f.firebasestorage.app',
    measurementId: 'G-TH8TB2GWSC',
  );
}
